name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compile_args:
           - ""
           - "-D ASCII_CHECK_SSE41 -msse4.1"
    steps:
      - uses: actions/checkout@v2
      - name: compile test suite
        run: gcc ${{matrix.compile_args}} test_ascii_check.c -o test_ascii_check
      - name: run tests
        run: ./test_ascii_check
