name: CI

on: [push, pull_request]

jobs:
  test-unix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        compile_args:
           - ""
           - "-D ASCII_CHECK_SSE2 -msse2"
    steps:
      - uses: actions/checkout@v2
      - name: compile test suite
        run: >- 
          cc -Wall -Werror 
          ${{matrix.compile_args}} 
          test_ascii_check.c -o test_ascii_check
      - name: run tests
        run: ./test_ascii_check

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compile_args:
          - ""
          - "/D ASCII_CHECK_SSE2"
    steps:
      - uses: actions/checkout@v2
      - name: Set MSVC developer prompt
        uses: ilammy/msvc-dev-cmd@v1.6.0
      - name: compile test suite
        run: >-
          cl ${{matrix.compile_args}} 
          test_ascii_check.c
      - name: run tests
        run: .\test_ascii_check
